jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          BASE_URL: /worst-ux/
